# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "pt-br"

# HTML Title
title: "Mylena Angélica"

# Avatar image path
avatar: "./images/mylena.jpeg"

# Name section text
name: "@mylena-angelica"

# Tagline section text
tagline: >-
    An software engineer from Brazil 🇧🇷 who loves inovation, sustainability, artificial intelligence, gamification and much more.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-linkedin"
      text: "LinkedIn"
      url: "https://www.linkedin.com/in/mylena-angelica/"
      alt: "Mylena's LinkedIn"
      title: "Mylena's LinkedIn"
      target: "_blank"
  - link:
      icon: "fa-solid fa-envelope"
      text: "Email"
      url: "mailto:mylena.asf@gmail.com"
      alt: "Email: mylena.asf@gmail.com"
      title: "Email: mylena.asf@gmail.com"
      target: "_blank"
  - link:
      icon: "fa-brands fa-telegram"
      text: "Telegram"
      url: "https://zhgchg.li/"
      alt: "Mylena's Telegram"
      title: "Mylena's Telegram"
      target: "_blank"
 - link:
      icon: "fa-brands fa-github"
      text: "Github"
      url: "https://github.com/Mylena-angelica/"
      alt: "Mylena's GitHub"
      title: "Mylena's GitHub"
      target: "_blank"
  - link:
      icon: "fa-brands fa-github"
      text: "Salsa"
      url: "https://github.com/Mylena-angelica/"
      alt: "Mylena's Salsa"
      title: "Mylena's Salsa"
      target: "_blank"
  - link:
      icon: "fa-brands fa-app-store-ios"
      text: "Slides"
      url: "https://github.com/ZhgChgLi/ZReviewTender"
      alt: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
      title: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/Mylena-angelica/"
      title: "Mylena's GitHub"
      alt: "Mylena's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/mylena-angelica/"
      title: "Mylena's LinkedIn"
      alt: "Mylena's LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/mylys2/"
      title: "Instagram"
      alt: "Mylena's Instagram"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:mylena.asf@gmail.com"
      title: "Email: mylena.asf@gmail.com"
      alt: "mylena.asf@gmail.com"
      target: "_blank"

# Footer text
footer: >
    Hi there! Follow me on LinkedIn, GitHub, Instagram  or stay connected on Email or Telegram.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
